DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE fault (
  id BIGSERIAL PRIMARY KEY,
  cause VARCHAR NOT NULL,
  occurred VARCHAR NOT NULL
);

CREATE TABLE account (
  id BIGSERIAL PRIMARY KEY,
  license CHAR(36) UNIQUE NOT NULL,
  email VARCHAR NOT NULL,
  pin CHAR(7) NOT NULL,
  activated VARCHAR(10) NOT NULL
);

CREATE TABLE survey (
  id BIGSERIAL PRIMARY KEY,
  account_id BIGINT REFERENCES account(id),
  title VARCHAR NOT NULL,
  created VARCHAR(10) NOT NULL,
  released VARCHAR(10) NOT NULL
);